env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:vue/essential
  - google
parserOptions:
  ecmaVersion: 13
  parser: '@typescript-eslint/parser'
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
